# Generated by Django 5.1.4 on 2025-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
